tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "fd"
brew "fish"
brew "fzf"
brew "neovim"
brew "python@3.10", link: true
brew "tmux"
cask "alacritty"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "sublime-merge"
cask "sublime-text"
