#!/bin/sh +x

determinePort() {
  port=3306
  case $1 in
    achievements-db*)
    port=33060
    ;;

    audi-ac-db*)
    port=33060
    ;;

    appversion-db*)
    port=33061
    ;;

    appversion-documentdb*)
    port=27011
    ;;

    audi-av-db*)
    port=33061
    ;;

    challenges-db*)
    port=33062
    ;;

    audi-cl-db*)
    port=33062
    ;;

    challenges-documentdb*)
    port=27012
    ;;

    configuration-db*)
    port=33018
    ;;

    dmp-db*)
    port=33063
    ;;

    audi-dmp-database*)
    port=33063
    ;;

    driverlog-db*)
    port=33064
    ;;

    driverlog-documentdb*)
    port=27014
    ;;

    fuellog-db*)
    port=33065
    ;;

    audi-fl-db*)
    port=33065
    ;;

    identity-db*)
    port=33066
    ;;

    lastparkingposition-db*)
    port=33067
    ;;

    audi-lpp-db*)
    port=33067
    ;;

    user-service-db*)
    port=33011
    ;;

    utility-db*)
    port=33012
    ;;

    vwsystems-db*)
    port=33014
    ;;

    vwsystems-documentdb*)
    port=20715
    ;;

    audi-vws-db*)
    port=33014
    ;;

    vehicle-db*)
    port=33015
    ;;

    migration-db*)
    port=33016
    ;;


    levelup-db*)
    port=33017
    ;;

    terms-of-use-db*)
    port=33018
    ;;

    servicelead-db*)
    port=33019
    ;;

    driverlog_db)
    port=20714
    ;;

  esac
}

if [[ "$1" == '' ]]; then
    echo "Usage: $0 <name-of-database-service>"
fi

determinePort "$1"

target=mysql-docker
if [[ $1 != *"-int"* ]]; then
    target=mysql-docker-prod
    port=$((port-10000))
fi

cf-connect "$1" -p "$port" -t $target
